# NUMPY
## Core Functionalities of Numpy
1. Broadcasting
2. Usage of SIMD in the np.where which makes the operations 200 times faster
## Functions that are not used from the array
1. np.array
2. np.unravel_array
3. np.linspace #not linespace
4. np.arange # not arrange
5. np.where()
6. np.unique()
7. np.concatenate()
8. np.hstack(), np.vstack()
9. np.split()
10. np.vsplit(), np.hsplit()
11. np.clip()
12. np.argsort()
13. np.bincount()
## Function that are used from the array
1. array.shape
2. array.dtype
3. array.repshape(a, b, c)
4. array.mean(), array.std()
5. array.min(), array.max()
6. array.argmin(), array.argmax()

In [2]:
import numpy as np

In [3]:
#1
l = [i for i in range(1000)]
a = np.array(l, dtype = np.float32).reshape(250, 4)
print(a.shape)
print(a.dtype)

#2
l = [[[i + j + k for k in range(2)] for j in range(3)] for i in range(4)]
b = np.array(l).reshape(6, 4)
print(b.shape)

#3
a = np.linspace(-1, 1, 100).reshape(20, 5)
# print(a)

#4
b = np.arange(0, 30, 1)
b = b.reshape(5, 2, 3)
print(b[1])

#5
a = np.arange(100, 130, 1)
a = a.reshape(3, 2, 5)


#6
b = [a[i].mean() for i in range(3)]
print(b)

b = a[1]
b = [b[i].mean() for i in range(2)]
print(b)


#7
b = a[0].std(axis = 0)
print(b)
b = a[0].std(axis = 1)
print(b)
mean = a[0].mean(axis = 1, keepdims = True)
a[0] = a[0] - mean
print(a[0])

#8 
b = a.max()
print(b)
b = a.argmax()
print(np.unravel_index(b, a.shape))
b = a.min()
print(b)
b = a.argmin()
print(b)

#9
np.where(a < 120, 0, a)

#10
values, counts = np.unique(a[1], return_counts = True)
dic = dict(zip(values, counts))

print(values, counts, dic)
print(dic[114])

#11
print(a[0], a[1])
b = np.concatenate((a[0], a[1]), axis = 0)
print(b)
b = np.hstack((a[0], a[1]))
b = np.vstack((a[0], a[1]))
print(b)

#12
b = np.split(a[0], 5, axis = 1)
print(b)
b = np.vsplit(a[0], 2)
print(b)
b = np.hsplit(a[0], 5)
print(b)

#13
c = np.array(([2, 3], [4, 6]))
print(c.shape)
d = np.tile(c, (3, 3))
print(d)
e = np.repeat(c, 2, axis = 0)
print(e)

#14
a = np.arange(10, 30).reshape(4, 5)
print(a)
b = a > 20
print(b)
b = np.where(a > 15, a, -1)
print(b)

#15 --- Broadcasting
a = np.array(([1, 2, 3], [2, 5, 10]))
b = np.array(([1]))
c = a + b
print(c)

#16
a = np.arange(20).reshape(4, 5)
print(a)
b = a.mean(axis = 0)
print(b)
c = a - b
print(c)
d = a.std(axis = 0)
c = c / d
print(c)

#Inplace Z score
a = (a - a.mean(axis = 0))/a.std(axis = 0)
print(a)

#clipping
a = np.where(a > 1.5, 1.5, a)
a = np.where(a < -1.5, -1.5, a)
print(a)
a_bef = a.copy()
a = np.clip(a, -1.5, 1.5)
b = np.where(a != a_bef, 1, 0)
print(np.sum(b))

#21
percent = (np.sum(b)/np.size(a)) * 100
print(percent)

#22
a = np.array(([10, 5, 3, 8, 9]))
b = np.argsort(a)
print(a, b)

#23
mask = b == 1
c = a[mask]
print(c)

#24
labels = np.array([1, 5, 1, 1, 2, 5, 1])
b = np.bincount(labels)
print(b)

#25
a = np.random.randint(0, 20, (4, 5))
print(a.mean(axis = 0), a.mean(axis = 1))
print(a.std(axis = 0) ** 2, a.std(axis = 1) ** 2)
print(a.var(axis = 0), a.var(axis = 1))

(250, 4)
float32
(6, 4)
[[ 6  7  8]
 [ 9 10 11]]
[np.float64(104.5), np.float64(114.5), np.float64(124.5)]
[np.float64(112.0), np.float64(117.0)]
[2.5 2.5 2.5 2.5 2.5]
[1.41421356 1.41421356]
[[-2 -1  0  1  2]
 [-2 -1  0  1  2]]
129
(np.int64(2), np.int64(1), np.int64(4))
-2
0
[110 111 112 113 114 115 116 117 118 119] [1 1 1 1 1 1 1 1 1 1] {np.int64(110): np.int64(1), np.int64(111): np.int64(1), np.int64(112): np.int64(1), np.int64(113): np.int64(1), np.int64(114): np.int64(1), np.int64(115): np.int64(1), np.int64(116): np.int64(1), np.int64(117): np.int64(1), np.int64(118): np.int64(1), np.int64(119): np.int64(1)}
1
[[-2 -1  0  1  2]
 [-2 -1  0  1  2]] [[110 111 112 113 114]
 [115 116 117 118 119]]
[[ -2  -1   0   1   2]
 [ -2  -1   0   1   2]
 [110 111 112 113 114]
 [115 116 117 118 119]]
[[ -2  -1   0   1   2]
 [ -2  -1   0   1   2]
 [110 111 112 113 114]
 [115 116 117 118 119]]
[array([[-2],
       [-2]]), array([[-1],
       [-1]]), array([[0],
       [0]]), array([[1],
       [1]

In [19]:
#New Doubts
#1
a = np.arange(15, 30).reshape(5, 3)
print(a)
y = np.arange(1, 4).reshape(3, 1)
print(y)
mask = a[:, 2] > 18
print(mask)
print(mask.squeeze().T)
print(a[mask, :])
print(y.T[mask])


X_type = np.array(([1, 0, 0]))
print(X_type[mask])

[[15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]
[[1]
 [2]
 [3]]
[False  True  True  True  True]
[False  True  True  True  True]
[[18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]
[[1 2 3]]


IndexError: boolean index did not match indexed array along axis 0; size of axis is 3 but size of corresponding boolean axis is 5